name: flutter_assessment
description: Flutter assessment.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^0.13.4
  flutter_slidable: ^1.2.0
  sqflite: ^2.0.2
  path_provider: ^2.0.9
  hive: ^2.0.6
  hive_flutter: ^1.1.0
  url_launcher: ^6.0.20
  equatable: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  build_runner: ^2.1.7
  hive_generator: ^1.1.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/no_contact.png

